### PR TITLE
Feat/add useCookie composable

### PR DESCRIPTION
**Pull request by jy0529**
Hi, pikax

I added a new composable that is useCookie,  it used js-cookie library.

can you review this PR?

### CODE REVIEW

**Comment by pikax** [comment]
Thank you for the PR, this one is a bit tricky because of the dependency to `js-cookie`.

`vue-composable` package should be dependency free (apart from vue) , but you can have it in other package (similar to `@vue-composable/axios`)  where we can wrap it

**Comment by jy0529** [comment]
> Thank you for the PR, this one is a bit tricky because of the dependency to `js-cookie`.
> 
> `vue-composable` package should be dependency free (apart from vue) , but you can have it in other package (similar to `@vue-composable/axios`) where we can wrap it

Thank you, I will contribute after learn @vue-composable/axios.🤗

**Comment by jy0529** [comment]
Hi, pikax

I added a new repo for useCookie and I learned a lot.

**Review by pikax — APPROVED** [review]
Thank you, sorry for the delay. 

Made a few changes

**Comment by jy0529** [comment]
> Thank you, sorry for the delay.
> 
> Made a few changes

It's ok.

In china, these day are new year's day, best wish for you.

**Comment by jy0529** [comment]
> Thank you, sorry for the delay.
> 
> Made a few changes

It's ok.

In china, these day are new year's day, best wish for you.

**Pull request merged**
