### PR TITLE
fix: deps, axios

### PR DESCRIPTION
**Pull request by blowsie**
axios is used outside of development
https://github.com/pikax/vue-composable/blob/master/src/web/axios.ts

### CODE REVIEW

**Comment by blowsie** [comment]
does open up a question, should this project be a mono repo or similar to prevent unwanted deps?

**Comment by pikax** [comment]
Yes, I will be converting to a monorepo for this cases for example `axios` and `web`

**Comment by blowsie** [comment]
also, sorry i broke your tests
https://circleci.com/gh/pikax/vue-composable/152

**Comment by pikax** [comment]
no worries I will update the package.json and re-add to `devDependencies`

In regards to monorepo I will just finish the current open PR and will start working on that, I want to release `0.3.0` to be able to break it down for v1 :)

**Comment by blowsie** [comment]
Perhaps i should have put it in `dependencies` instead of `peerDependencies`

**Comment by pikax** [comment]
it should be dev-dependencies, just `vue` and `@vue/composition-api` dependencies

**Comment by blowsie** [comment]
the problem is i had a module not found error when doind my first build after installing this package

**Comment by pikax** [comment]
because the rollup adds the import, I will create other library to handle `axios` and other third-parties

**Pull request merged**
