### PR TITLE
feat(composable): add a new composable

### PR DESCRIPTION
**Pull request by jy-js**
add a new compoasble useTimeout, #506

### CODE REVIEW

**Review by pikax — COMMENTED** [review]
LGTM 

My only nit pick are the tests, because of awaiting for a timer to run off, there's a change it won't be executed property.

Thank you,

**Comment by jy-js** [comment]
> LGTM
> 
> My only nit pick are the tests, because of awaiting for a timer to run off, there's a change it won't be executed property.
> 
> Thank you,

wow, thanks, I will learn more about jest, and I refactor this tests, do you think this well?

`describe("timeout", () => {
  beforeAll(() => {
    jest.useFakeTimers();
  });

  afterEach(() => {
    jest.clearAllTimers();
  });

  afterAll(() => {
    jest.useRealTimers();
  });

  it("should be defined", () => {
    expect(useTimeout).toBeDefined();
  });

  it("should call passed function after given amount of time", () => {
    const callback = jest.fn();

    useTimeout(callback, 1000);

    expect(callback).not.toBeCalled();

    jest.advanceTimersByTime(1000);
    expect(callback).toBeCalled();
    expect(callback).toHaveBeenCalledTimes(1);
  });
  ......more tests
}
`

**Comment by jy-js** [comment]
you work so fast!

**Comment by pikax** [comment]
> wow, thanks, I will learn more about jest, and I refactor this tests, do you think this well?

Yep, I added it https://github.com/pikax/vue-composable/pull/740/commits/0636f68f6584357014d329ca4501f635da1acaf8  :)

**Pull request merged**
